name: media-server

services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    env_file:
      - .env
    hostname: nordlynx
    container_name: nordlynx
    ports:
      - 8095:8095
    cap_add:
      - NET_ADMIN
#        - SYS_MODULE
    environment:
      - PRIVATE_KEY=${NORDVPN_PRIVATE_KEY:-EMPTY}
      - COUNTRY_CODE=${COUNTRY_CODE:-UA}
      - NET_LOCAL=192.168.2.0/24
      - TZ=Europe/Lisbon
    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1   # maybe
#      - net.ipv4.conf.all.rp_filter=2        # maybe; set reverse path filter to loose mode
      - net.ipv6.conf.all.disable_ipv6=1     # disable ipv6; recommended if using ipv4 only
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-latest
    container_name: qbittorrent
    depends_on:
      - nordlynx
    network_mode: service:nordlynx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - WEBUI_PORT=8095
    volumes:
      - ~/qbittorrent/config:/config
      - ~/qbittorrent/downloads:/downloads
      - /mnt/mediahdd:/mnt/mediahdd
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: "bridge"
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - /mnt/mediahdd:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - 8096:8096
    restart: unless-stopped

