name: media-server

services:
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn:latest
    env_file:
      - .env
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=${NORDVPN_TOKEN:-EMPTY}
      - CONNECT=${VPNCOUNTRY:-UKRAINE}
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    #restart: unless-stopped
    ports:
      - 8080:8080
#    sysctls:
#      - net.ipv6.conf.all.disable_ipv6=1

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:arm64v8-latest
    container_name: qbittorrent
    depends_on:
      - nordvpn
    network_mode: "service:nordvpn"
#    ports:
#      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - WEBUI_PORT=8080
    volumes:
      - ~/qbittorrent/config:/config
      - ~/qbittorrent/downloads:/downloads
    #restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: "bridge"
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - /mnt/mediahdd:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - 8096:8096
    #restart: unless-stopped

